### ISSUE TITLE
monaca serve

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#10]
How does this work? According to the description, it sounds like `monaca livesync`. When I tried it, there are many errors.

**Comment by argelius** [comment]
Oh!

Can you paste the errors?

**Comment by khemry** [comment]
1. I navigate to my project folder
2. type "monaca serve"
   here is the error:

Installing packages. Please wait. This might take a couple of minutes.
npm
 WARN package.json onsenapp@0.0.0 No description
npm WARN package.json onsenapp@0.0.0 No repository field.
npm WARN package.json onsenapp@0.0.0 No README data

npm
 ERR! Error: EACCES, mkdir '/Users/Khemry/.npm/stylus/0.51.0'

npm 
ERR!
  { [Error: EACCES, mkdir '/Users/Khemry/.npm/stylus/0.51.0']
npm
 ERR!   errno: 3,

npm ERR!
   code: 'EACCES',
npm 
ERR!   path: '/Users/Khemry/.npm/stylus/0.51.0',

npm ERR!
   parent: 'gulp-stylus' }

npm 
ERR! 

npm 
ERR!
 Please try running this command again as root/Administrator.

npm

ERR! System
 Darwin 14.0.0

npm
 ERR! command
 "node" "/usr/local/bin/npm" "install"
npm
 ERR!
 cwd
 /Users/Khemry/Documents/monaca_cli/projects/new_project

npm 
ERR! node -v v0.10.31

npm 
ERR! npm -v
 1.4.23

npm
 ERR! 
path /Users/Khemry/.npm/stylus/0.51.0

npm 
ERR! code
 EACCES

npm ERR!
 errno 3

npm ERR! stack Error: EACCES, mkdir '/Users/Khemry/.npm/stylus/0.51.0'

npm
 ERR! 

npm ERR!
 Additional logging details can be found in:

npm ERR!
     /Users/Khemry/Documents/monaca_cli/projects/new_project/npm-debug.log

npm ERR! 
not ok
 code 0

**Comment by argelius** [comment]
Thanks! It's a permission problem. I will display a better message so the user can fix it.
