### ISSUE TITLE
monaca_config.json missing after install

### ISSUE THREAD

**Issue by waynethompson** [monaca/monaca-cli#104]
After installing the cli on a Windows10 machine and running any of the monaca commands I get the error 

>ENOENT: no such file or directory, open 'C:\Users\[User]\.cordova\monaca_config.json'

Looking in the .cordova folder I can see monaca.json

I copied monaca.json to monaca_config.json and the error was fixed.

**Comment by andipavllo** [comment]
This is very weird. Could you please tell us how did you install `monaca-cli`? Was it the first time or you were upgrading?

**Comment by waynethompson** [comment]
It was a new install on windows 10 using npm.

I have a machine that I have just reinstalled the latest windows 10 so I will try to replicate the problem.

**Comment by andipavllo** [comment]
Thanks! Please let us know how it goes.

**Comment by waynethompson** [comment]
A similar error happened after a new install on osx.

I notice after running the command the file exists but only contains a blank object
{}

I tested on Ubuntu 17.04 and noticed the same behaviour so without looking at the code I asume that is what it is meant to do. 

Now I am testing on Windows 10 again

![monaca error](https://user-images.githubusercontent.com/6680492/28991443-008fc6ee-79cb-11e7-8ebb-283e03049f6b.png)

**Comment by andipavllo** [comment]
Yeah, an empty object is the correct behavior. I will try to make reproduce the issue on Windows and let you know. In the meanwhile, please check if your current authenticated user has WRITE privilege in the .cordova dir location.

Update: just tried to perform a fresh installation on Windows 10 by using Powershell and had no issues. The file was correctly created.

**Comment by andipavllo** [comment]
Closing this for now, feel free to provide additional information in case you are still encountering the issue.
