### ISSUE TITLE
Error during login and signup

### ISSUE THREAD

**Issue by dipbhi** [monaca/monaca-cli#109]
monaca cli version: 2.4.1
OS: Windows 10

Below errors are being returned by login and signup commands
Login generates ENOTFOUND error
Signup generates ECONNREFUSED error

Screenshot is attached as a reference.
![monaca error](https://user-images.githubusercontent.com/12301512/29994581-62fb8d3c-8ff0-11e7-8a5d-74b6714ec77a.png)

**Comment by andipavllo** [comment]
Did you set up an API endpoint by mistake or have problems with the internet connection? Did you try using another network?
To reset the API endpoint run `monaca config endpoint --reset`

**Comment by dipbhi** [comment]
Thank you very much. This command fixed it for me.

monaca config endpoint --reset

I don't recall setting API endpoint but cannot be sure if it got set unintentionally while creating a sample app.
