### ISSUE TITLE
monaca upload

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#11]
when I tried to upload a project, this sentence appears:
"Do you want to continue? (y/N)" 

It should be (Y/N), right? As I tried, it's case sensitive.

**Comment by argelius** [comment]
Capital letter implies default choice. I think this is common practice in command line tools.

**Comment by argelius** [comment]
But if it's case sensitive that's not correct so I will fix that.

**Comment by khemry** [comment]
One more thing, I can upload one project at a time, right? 

Let  say I have a folder (projects/) with 2 new projects, can I navigate to "projects/" and use "monaca upload" to upload these two new projects? 

As I tried, it failed but the error message is vague:
"Upload failed: EMFILE"

**Comment by argelius** [comment]
Fixed.
