### ISSUE TITLE
how to make console.log working?

### ISSUE THREAD

**Issue by hirbod** [monaca/monaca-cli#110]
Since I've installed monaca, I can't get any console.log inside of Safari Debugger.
All I see are error messages on "monaca://log"

The cordova console plugin doesn't work either. What can I do? Thanks!

**Comment by andipavllo** [comment]
I don't think that's related to Monaca CLI. How are you serving your project and what kind of project are you exactly debugging?
I suggest you to contact the Monaca Support [here](https://monaca.io/service/)
