### ISSUE TITLE
Monaca 2.4.6 is not running vue templates while 2.4.1 is

### ISSUE THREAD

**Issue by pashute** [monaca/monaca-cli#119]
Monaca 2.4.6 is not running vue templates, while 2.4.1 cli is. 
I saw that vue-onsenui was not properly working so did npm outdated and updated/installed all latest npm packages. 

I then run `npm install` and after that `monaca preview`  and get `import error  - in babel`

Do I need to downgrade? 

I run ok with monaca 2.4.1 cli. My packages read     

    {
        "name": "onsenui-v2-vue-minimum",
        "version": "2.4.0+20170901.1",
        "description": "",
        "dependencies": {
          "onsenui": "2.6.1",
          "vue": "^2.4.4",
          "vue-loader": "13.0.5",
          "vue-onsenui": "^2.2.1",
          "vue-template-compiler": "^2.4.4",
          "vuex": "^3.0.0"
        }
    }

running `npm outdated` I get: 

    vue-loader             MISSING  13.0.5  13.3.0  onsenui-v2-vue-minimum
    onsenui                  2.6.1   2.6.1   2.7.0  onsenui-v2-vue-minimum
    vue                      2.4.4   2.5.2   2.5.2  onsenui-v2-vue-minimum
    vue-onsenui              2.2.1   2.3.0   2.3.0  onsenui-v2-vue-minimum
    vue-template-compiler    2.4.4   2.5.2   2.5.2  onsenui-v2-vue-minimum

**Comment by pashute** [comment]
I now know 4 experienced VUE programmers (besides myself) that regrettably are moving back to ionic because they can't run vue-onsenui projects. 

See here for an example: (on the features/wireframe branch) : https://github.com/pashute/noam.vue098/tree/features/wireframe

**Comment by andipavllo** [comment]
I invite you to check the changelog of the dependencies you are updating. These templates use `vue-loader 11.0.0` but you are updating to`13.x`, which introduces some [breaking changes](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0). You may want to adjust your project configuration after checking the official documentation, [here](https://github.com/OnsenUI/OnsenUI/commit/edd78ca283ed4bad5440461d037c1e06577e459b) is an example. Monaca CLI seems working fine.

**Comment by pashute** [comment]
will check and see.
