### ISSUE TITLE
monaca multiserve

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#12]
As i notice, `monaca serve` is for the browser while `monaca multiserve` is for Monaca debugger?
I am unable to confirm how `monaca multiserve` works as the process seems to just stuck. It's been 10mn till now. Here is the message:

$ monaca multiserve ibeacon tab_bar 

Starting file listening.
Starting HTTP server.
Listening on 10.0.1.12:8001
Starting beacon transmitter.
Waiting for connections from Monaca debugger...
Debugger requested project list.

**Comment by argelius** [comment]
Thanks again @khemry!

**Comment by argelius** [comment]
This works when I try it. Please help me reproduce it, @khemry .
