### ISSUE TITLE
Monaca cli broken on latest nodejs and npm

### ISSUE THREAD

**Issue by pashute** [monaca/monaca-cli#121]
nodejs 8.5.0
npm 5.4.2

Monaca Create:  I get an error message `Error in getting project templates list:500`
In a project made on a different pc: Monaca Preview gives: 
Project preview failed: Cannot find module 'C:\Users\Win\.cordova\node-modules\webpack'

npm install -g webpack works but installs it to C:\Users\Win. 
There is a .cordova path...

Notes: 
* I'm installing on a system with ionic, so Cordova was installed previously somewhere else. Could that be the cause?
* I'm installing on drive D:  and the node/npm is on disck c:\program files...   could that be the cause?

**Comment by andipavllo** [comment]
We acknowledge the template issue and are working on a fix. It's actually not related to node/npm but it's a backend issue. It's requiring you to be logged in while that should not be necessary. As a temporary workaround, just run `monaca login` and you should be able to access the template list.

For the webpack issue, Monaca uses its own version so running `npm install -g webpack` will not affect it at all. Monaca CLI does not actually use the default cordova files/config but it creates its own under the user home directory. Try running `monaca reconfigure` from inside your project and see if it solves the issue.

**Comment by pashute** [comment]
Sadly, this was a show-stopper and I currently moved off Monaca.
