### ISSUE TITLE
Remote builds with crosswalk fail for Android.

### ISSUE THREAD

**Issue by munsterlander** [monaca/monaca-cli#122]
Based on this thread, https://community.onsen.io/topic/1868/build-is-successful-but-postbuild-fails-crosswalk-getusermedia-and-trackstarterror there is an error with crosswalk builds via the Cloud IDE.

**Comment by andipavllo** [comment]
@munsterlander sorry for the late reply. This as well isn't really a CLI issue. Would you mind contacting directly Monaca Support at the following [link](https://monaca.io/support/technical/)? Thank you very much.
