### ISSUE TITLE
Release build doesn't honor config.xml with custom-config plugin per docs

### ISSUE THREAD

**Issue by munsterlander** [monaca/monaca-cli#123]
So based on this thread, https://community.onsen.io/topic/1871/release-build-removes-camera-permission with the custom-config plugin and the Cloud IDE, on a release build, the CAMERA permission is never added to the AndroidManifest.xml.  Other permissions do make it though.

**Comment by andipavllo** [comment]
@munsterlander sorry for the late reply. This isn't really a CLI issue. Would you mind contacting directly Monaca Support at the following [link](https://monaca.io/support/technical/)? Thank you very much.
