### ISSUE TITLE
Select a template - previews don't work

### ISSUE THREAD

**Issue by kmfreas** [monaca/monaca-cli#124]
Just letting you know the previews don't work when you are picking a template for Onsen UI and Vue.js. I got to them by running monaca create example and selecting Onsen UI and Vue.js.

Here's an [example](https://template.monaca.mobi/onsenui-v2-vue-splitter/)

**Comment by andipavllo** [comment]
I just tried to preview the template you mentioned and it seems working fine. What issue did you encounter?

**Comment by kmfreas** [comment]
Huh, it just doesn't load for me, I get a blank white screen. Thinking it may be just me, I opened it up in browserstack but the same issue happens. 
![selection_010](https://user-images.githubusercontent.com/1760767/35630413-587ea2cc-066f-11e8-80b6-70df202b0697.jpg)
