### ISSUE TITLE
Could not install latest 

### ISSUE THREAD

**Issue by berrg** [monaca/monaca-cli#125]
npm install -g monaca@
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! path C:\Users\Morten\AppData\Roaming\npm\node_modules\monaca\node_modules\npm\node_modules\ansistyles
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Morten\AppData\Roaming\npm\node_modules\monaca\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\Morten\AppData\Roaming\npm\node_modules\monaca\node_modules\npm\node_modules\.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Morten\AppData\Roaming\npm-cache\_logs\2018-02-02T08_26_56_789Z-debug.log

**Comment by tehg00se** [comment]
Same issue

`npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/monaca/node_modules/npm/node_modules/ansistyles' -> '/usr/local/lib/node_modules/monaca/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:`

**Comment by DarkPurple141** [comment]
+1.  Exact same issue.

**Comment by fabiendeborde** [comment]
Same problem here.

**Comment by erisu** [comment]
There is currently an open bug ticket with NPM around this install issue.

https://github.com/npm/npm/issues/17444

The current workaround is to uninstall before installing the newest version.

```
$ npm uninstall -g monaca
$ npm install -g monaca
```

**Comment by isaacetukudo** [comment]
thank u @erisu, it worked for me...
