### ISSUE TITLE
Does monaca-cli work on Ubuntu Linux?

### ISSUE THREAD

**Issue by softwareishappiness** [monaca/monaca-cli#127]
We would seriously consider Monaca if the LocalKit CLI officially works on Linux.

**Comment by yong-asial** [comment]
@softwareishappiness Sorry for the late reply.  `monaca-cli` is working fine on Linux. And I've just managed to build the `Monaca Localkit` in linux version. You can download it here - https://github.com/monaca/Localkit/releases/download/3.1.1/monaca-localkit_3.1.1_amd64.deb

Other Localkit distributions: https://github.com/monaca/Localkit/releases
