### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by rodolfojnn** [monaca/monaca-cli#13]
On running "npm install -g monaca", I received the ENOENT error. From npm-debug.log:

81 error Windows_NT 6.1.7601
82 error argv "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "monaca"
83 error node v0.12.3
84 error npm  v2.9.1
85 error path C:\Users\rodolfo\AppData\Roaming\npm\node_modules\monaca:q
86 error code ENOENT
87 error errno -4058
88 error enoent ENOENT, open 'C:\Users\rodolfo\AppData\Roaming\npm\node_modules\monaca:q'
88 error enoent This is most likely not a problem with npm itself
88 error enoent and is related to npm not being able to find a file.
89 verbose exit [ -4058, true ]

**Comment by rodolfojnn** [comment]
npm install -g monaca@1.0.4 works.

**Comment by argelius** [comment]
Thank you @rodolfojnn ! I will take a look at this

**Comment by argelius** [comment]
I've published a working version now. I don't really know what happened but I will be more careful when publishing now :)

Thanks @rodolfojnn !
