### ISSUE TITLE
Add concurrent remote building of multiple platforms

### ISSUE THREAD

**Issue by corycaywood** [monaca/monaca-cli#131]
The `monaca remote build` command currently only accepts one platform as an argument. It would be more convenient if it could build multiple platforms at once, i.e. `monaca remote build android ios`.

**Who:** App developers using Monaca CLI.
**What:** Want to build more than one platform concurrently.
**Why:** It is faster and more convenient to build all platforms concurrently than to run the remote build command one after another for each platform. This is particularly useful if using Monaca CLI on a continuous integration machine.

### Criteria
- Should allow one or more platforms to be specified after `monaca remote build`
- Should trigger remote build on Monaca for all specified platforms and download the binaries for each after it is successfully built
- Should exit with success code if all platform builds succeeded
- Should exit with error code if one or more of the platform builds failed

**Comment by corycaywood** [comment]
Hi @masahirotanaka : We would like to work on integrating these features. What do you think about this feature and the suggested criteria?

**Comment by yong-asial** [comment]
hi @corycaywood 
That's a good idea. We would be really appreciated if you can create a PR and we will then review and merge it.
