### ISSUE TITLE
Add option for saving build logs to file

### ISSUE THREAD

**Issue by corycaywood** [monaca/monaca-cli#132]
The Monaca CLI doesn't currently provide a way of viewing build logs when using `monaca remote build`. In order to view the log, the app developer must login to the Cloud IDE and find the build. It would be more convenient if the log could be downloaded via Monaca CLI.

**Who:** App developers using Monaca CLI.
**What:** Want to save the Monaca build logs to the machine which is running Monaca CLI.
**Why:** It allows developers to more easily debug when build errors occur. This is particularly useful on a continuous integration machine.

### Criteria
- Should add a `--save-logs` option to the `monaca remote build` command
- Should download the build log after a platform is built successfully or fails to build
- Should save the build log to the same location as the platform binaries using the file name `[binary file name]-log.txt`. (for example: `20180704164552-android-debug-log.txt`)

**Comment by corycaywood** [comment]
Hi @masahirotanaka : We would like to work on integrating this. What do you think about this feature and the suggested criteria?

**Comment by yong-asial** [comment]
hi @corycaywood 
That's a good idea. We would be really appreciated if you can create a PR and we will then review and merge it.
