### ISSUE TITLE
Command monaca preview is not working

### ISSUE THREAD

**Issue by incoming-th** [monaca/monaca-cli#140]
Hi,

I've updated a project from monaca cli 2 to 3. All seems fine, but when I tried monaca preview it just backs to the command line, nothing happened.

Did I missed a step?

![2018-10-18 003278](https://user-images.githubusercontent.com/26375917/47146310-01df4f80-d2f6-11e8-85cf-4b0347a4c8e1.png)

Log of the update processes:

![2018-10-18 003279](https://user-images.githubusercontent.com/26375917/47146821-0b1cec00-d2f7-11e8-97cc-485bd32aceac.png)
![2018-10-18 003280](https://user-images.githubusercontent.com/26375917/47146828-0ce6af80-d2f7-11e8-848f-3b6d65bdc321.png)

**Comment by yong-asial** [comment]
@MickaelTH after running `monaca update`, it created 3 main files - `monaca_preview.js`, `webpack.dev.new.config.js` and `webpack.dev.prod.config.js`. Your updated `package.json` might look similar to the following:
```
"scripts": {
    "monaca:preview": "npm run dev & npm run watch",
    "dev": "PORT=8080 node ./monaca_preview.js",
    "monaca:transpile": "npm run build",
    "build": "webpack --config ./webpack.prod.new.config.js",
    "monaca:debug": "npm run watch",
    "watch": "webpack --watch --config ./webpack.prod.new.config.js"
}
```
Thus, by default running the command `monaca preview` will maily running the script `monaca_preview.js` and `webpack` with the new file configuration `webpack.prod.new.config.js`.

If you have modified your webpack configuration files (i.e webpack.dev.config.js or webpack.prod.config.js), you might need to modify the new generated webpack config files (`webpack.dev.new.config.js` and `webpack.dev.prod.config.js`) to reflect it.

Ref: https://docs.monaca.io/en/release_notes/20180918_monaca_cli_3.0/#transpile-projects
