### ISSUE TITLE
Documentation or fixes when using Create React App

### ISSUE THREAD

**Issue by joeflack4** [monaca/monaca-cli#141]
I started w/ a _Create React App_ app, and then tried to apply Monaca.

Now I'm getting:

```
Failed to compile.

  TypeError: Cannot read property 'request' of undefined
```

I found a probable solution here: https://github.com/facebook/create-react-app/issues/2352

They're basically saying I shouldn't have webpack in my package.json if I'm using Create React App. I see that I do have it there. I'm assuming this came with Monaca.

**Comment by yong-asial** [comment]
@joeflack4 Could you provide me with more information?

However, with the latest version (`monaca@3.x`), a new command `monaca init` is added to migrate the projects from other platforms. Please refer to the step-by-step guidelines to migrate your React app - https://docs.monaca.io/en/products_guide/migration/react_migration/

**Comment by joeflack4** [comment]
Hello Yong. Sorry, I forgot to close this issue! I did find out about monaca 3.x and it is working great!
