### ISSUE TITLE
Error in getting project templates list: 500 

### ISSUE THREAD

**Issue by KhanIshaq** [monaca/monaca-cli#144]
Unable to create monaca project using command line
When running the below command, getting 500 error response
$ monaca create TestApp
Error in getting project templates list: 500

Monaca Version - 3.0.3
Node Version - 8.12.0
NPM Version - 6.4.1

**Comment by yong-asial** [comment]
@KhanIshaq  Could you try relogin (`monaca logout` and `monaca login`) first before trying running the command (`monaca create TestApp`).

**Comment by KhanIshaq** [comment]
@yong-asial   I have updated monaca to latest version using npm -g install monaca@3.0.4 
Executed the command "monaca login" with my credentials
After successful login, I am able to create project using the command "monaca create TestApp"

Thanks
