### ISSUE TITLE
Error in monaca debug with Framework 7 Vue template (work fine in monaca preview mode)

### ISSUE THREAD

**Issue by Cawet2** [monaca/monaca-cli#146]
Hi,
I've got an issue when running some test app in the monaca debug android App, with the templates "Framework 7 vue Webpack" and "Framework 7 vue Simple". 
They perfectly work in the preview mode . 

```$ Monaca create myMonacaApp
-> Framework 7 vue Simple
$ cd myMonacaApp
$ monaca preview
```
-> work fine in the browser
```
$ ctr+ c
$ monaca debug
```
-> this error is throw in the debug App : 
`'Uncaught SyntaxError: missing ) after arguement list
www/vendors~app.bundle.js:1 `

I tested with the "no framework" template and with the "Onsen UI vue Vue Minimum", no error are throw in the debugger and it working fine.

**Comment by yong-asial** [comment]
Hi @Cawet2 ,
May I know which version of `monaca-cli` and `monaca-debugger` you are testing with? If it is not the latest, could you try testing it again with the latest version?

**Comment by Cawet2** [comment]
monaca-debugger : 7.0.9
monaca-cli : 3.0.4
if needed : 
nvm : 10.7.0 (npm 6.4.0). 

I don't think it's from the debugger, I get a white screen after compiling with your tool and then install the .pkg on my phone. 

Here is my package.json after creating a project with the "Framework 7 Vue Webpack" template : 
```
{
  "name": "framework7-vue-webpack",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "cordova-custom-config": "5.0.2",
    "cordova-plugin-splashscreen": "5.0.1",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-plugin-statusbar": "2.4.1",
    "monaca-plugin-monaca-core": "3.2.1",
    "vue": "^2.5.17",
    "framework7": "^3.4.0",
    "framework7-icons": "^0.9.1",
    "framework7-vue": "^3.4.0",
    "material-design-icons": "^3.0.1"
  },
  "scripts": {
    "monaca:preview": "npm run dev & npm run watch",
    "monaca:transpile": "npm run build",
    "monaca:debug": "npm run watch",
    "dev": "webpack-serve --open",
    "build": "webpack --mode production",
    "watch": "webpack --watch --mode production",
    "copy-fonts": "cpy node_modules/framework7-icons/fonts/*.* src/fonts && cpy node_modules/material-design-icons/iconfont/*.{eot,ttf,woff,woff2} src/fonts",
    "prepare": "npm run copy-fonts"
  },
  "cordova": {
    "plugins": {
      "cordova-custom-config": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "monaca-plugin-monaca-core": {}
    }
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "cordova": "^7.1.0",
    "css-loader": "^1.0.0",
    "cssnano": "^4.0.2",
    "file-loader": "^1.1.11",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.4.1",
    "postcss-cssnext": "^3.1.0",
    "postcss-import": "^11.1.0",
    "postcss-loader": "^2.1.6",
    "postcss-url": "^7.3.2",
    "progress-bar-webpack-plugin": "^1.11.0",
    "style-loader": "^0.21.0",
    "vue-loader": "^15.2.4",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.16.1",
    "webpack-cli": "^3.0.8",
    "webpack-serve": "^2.0.2",
    "yargs": "^12.0.1",
    "cpy-cli": "^2.0.0"
  }
}
```
I tried to debug a little bit by myself by disabling all optimisation and minification  : 

webpack.config.js
```
  optimization: {
    // removeAvailableModules: true,
    // splitChunks: {
    //   chunks: 'all'
    // },
    // runtimeChunk: true,
    // removeEmptyChunks: true,
    // mergeDuplicateChunks: true,
    // providedExports: true,
    minimize:false
  },
```

The debugger target the ligne 184 in app.bundle.js for the same previous error i was talking about, witch is this one : 

`return string.toLowerCase().replace(/-(.)/g, (match, group1) => group1.toUpperCase());`

I'm new to the ES6 syntax workd's, but i think we can conclude that the app isn't compatible with ES6 or the script isn't converted properly into JS.  

Something with babel ?

Don't know what to do from now ^^

**Comment by yong-asial** [comment]
Hi @Cawet2 ,
Is the error result from the unmodified `Framework 7 Vue Webpack` template? I could not really reproduce it.

I think you have written some codes that causing the building issue. You may try following to debug it:
1) run `monaca transpile` or `npm run build` to compile your apps into `www` directory
2) If there are some errors during the transpiling/compiling process, the error should be output during the process
3) Then manually open www/index.html and check your browser's log.

I don't think it is the problem with ES6, but if you think so feel free to use non-ES6. For example, we can replace it by
```
function camelCase(input) { 
    return input.toLowerCase().replace(/-(.)/g, function(match, group1) {
        return group1.toUpperCase();
    });
}
```

**Comment by Cawet2** [comment]
> Is  the error result from the unmodified Framework 7 Vue Webpack template? 

Yep, I tried the debugger right after created the app, like so :
```
$ monaca create myApp
$ cd myApp
$ monaca debug

```
I already try to replace manualy the ES6 syntax for this line, but this just bring me to the next ES6 line, and anyway fixing code in the compiled source sound impractical^^.

I'm new to the hybridApp's world to, but I believe that  hybridapp use some kind of part from native browser of the OS to run the source code ? like chromium for android ?
So is the problem could be from my android? I'm using the FP open OS by Fairphone : https://code.fairphone.com/projects/fp-osos/
and I'm using the version without all the Google app and Google play service stuff, so instead, I'm using GsmCore https://github.com/microg/android_packages_apps_GmsCore/wiki#-gmscore

Otherwise, I compared the www/app.bundle.js file with the one of the "Onsen UI V2 Vue Minimum" template (witch is working perfectly on my Monaca debug).

In the app.bundle.js file of the "Onsen UI V2 Vue Minimum" template, I don't found any ES6 syntax. By looking further, the ES6 syntax code seem to be from the framework 7 modules library. 

Is there a way to configure webpack to use babel to transpile ES6 also from the node_modules folder ?

anyway thank for your support!

**Comment by Cawet2** [comment]
Sometime simply explaining the problem help to go further :) 

I the app.js file, I replace the imported framework 7 bundle file version by the minified version, then I installed the babel/polyfill lib and added it at the very beginning  of the app.js file : 

```
import "@babel/polyfill";

// Import Vue
import Vue from 'vue';

// Import F7
import Framework7 from 'framework7/js/framework7.min.js';

// Import F7 Vue Plugin
import Framework7Vue from 'framework7-vue/framework7-vue.min.js';

```
and... it's work ! \o/

Before to close the issue, have you got any idea  what ES6 syntax didn't work for me ?

**Comment by yong-asial** [comment]
hi @Cawet2 ,
sorry for the late reply. I'm glad you've fixed it.

Anyway, it seems to me that your android version doesn't support ES6. Also, thank a lot for pointing it out about Framework 7's ES6. It seems that we have to modify either the babel config or webpack config in order to transpile Framework 7 esm module (See [this](https://framework7.io/docs/installation.html#es-next) for more information).

Just for testing, maybe you can modify the webpack config as following
```
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        include: [
          path.resolve(__dirname, 'src'),
          path.resolve(__dirname, 'node_modules/framework7'),
          path.resolve(__dirname, 'node_modules/framework7-vue'),
          path.resolve(__dirname, 'node_modules/template7'),
          path.resolve(__dirname, 'node_modules/dom7'),
          path.resolve(__dirname, 'node_modules/ssr-window')
        ],
        use: [{
          loader: 'babel-loader',
          options: {
            presets: [ 'env' ]
          }
        }]
      },
```

You may consult the [official Framework 7 repo](https://github.com/framework7io/framework7-template-vue-webpack) for more in-depth webpack and babel configuration.
