### ISSUE TITLE
Add automatic "remote build" feature

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#15]
Currently `monaca remote build` displays a new window.
Instead of it, please add another remote build options as follows:

```
monaca remote build [platform] [build-type] [--android_webview] [--android_arch]
```

**Available platform:**
- ios
- android
- windows

**Available build type:**
- debug (for iOS, Android and Windows)
- test (for iOS only)
- release (for iOS, Android and Chrome Apps)

**Available options:**
- `--android_webview`
- `--android-arch`

It will call `Monaca.buildProject()` function to build the project. When the build is done, please show the download URL for the package.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka,

I have partially [implemented](https://github.com/monaca/monaca-cli/commit/5aad84337a59f2eeb2f4a706d5705fde851ab0bd) this. I want to know which method do I use to get the project_id?
- monaca-lib uses _internal_ method `localProperties.get(projectDir, 'project_id')` whenever project_id is needed  
- monaca-cli uses `monaca.getProjectId(cwd)` ~~which I think is no longer present in monaca-lib.~~ Which may not work if the project was created locally and never uploaded.

**Comment by masahirotanaka** [comment]
@argelius Sorry for bothering you. Do you have any idea how to get the Cloud Project ID in this case?

Just let me know if you already for got about it :)

**Comment by JW-Vinayak** [comment]
Hi @argelius and @masahirotanaka 

Please let me know if following flow could be used?

if `monaca.getProjectId(cwd)` doesn't return project id then 
- create new project in the cloud using `monaca.createProject()` which will provide new project id
- set this project id locally using `monaca.setProjectId()`
- upload this project `monaca.uploadProject()` 
- and finally call `monaca.buildProject()`

**Comment by masahirotanaka** [comment]
Seems to be correct. I'll ask @argelius and send a feedback to you.

**Comment by argelius** [comment]
@masahirotanaka @JW-Vinayak 

I think this looks correct.

**Comment by masahirotanaka** [comment]
Please still keep the current implementation if no options are specified.
Currently it looks like `monaca remote build` does not accept without `platform` and `build-type`.
If the user runs remote build without any parameters, simply follow the existing implementation (open a browser to finish the build process).
