### ISSUE TITLE
Could not execute (monaca demo)

### ISSUE THREAD

**Issue by garchomp-game** [monaca/monaca-cli#150]
In the latest version of monaca-cli 3.1, the (monaca demo) command could not be executed. For this reason, I downgraded the version and is currently checking with monaca-cli 2.4. I want you to be able to execute even the latest version.

**Comment by yong-asial** [comment]
As you can see from version 3, we have decoupled the logic of previewing and transpiling (building) to `package.json` as in `monaca:preview` and `monaca:transpile` script. You can easily create your own version of `monaca demo` script.
You can re-create it from our design here - https://github.com/monaca/monaca-cli/archive/2.7.14.zip (pages/demo/index.html)
