### ISSUE TITLE
Cordova Plugins not working in monaca

### ISSUE THREAD

**Issue by bytedeveloperr** [monaca/monaca-cli#155]
please help!
I installed cordova-plugin-file with
`monaca plugin add cordova-plugin-file`
then after i used
`alert("Folders" + cordova.file)`
but it doesn't work
![Screenshot_2019-10-26-20-57-42](https://user-images.githubusercontent.com/48928718/67626002-74560a00-f83d-11e9-91bd-86944926f625.png)

**Comment by yong-asial** [comment]
@jupiter-mic It is working normally. You just need to stringify the object. Try testing with following code snippet
```
    <script>
        document.addEventListener("deviceready", onDeviceReady, false);
        function onDeviceReady() {
            alert("Folders" + cordova.file);
            alert("Folder" + JSON.stringify(cordova.file));
        }
    </script>
```
