### ISSUE TITLE
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability

### ISSUE THREAD

**Issue by blgsyrmhnds** [monaca/monaca-cli#158]
Bug Report
Problem
We have updated the Cordova iOS library to the latest version in package.json ("cordova": "^9.0.0")
and the tag

<preference name="WKWebViewOnly" value="true"/>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine"/>
    <feature name="CDVWKWebViewEngine">
      <param name="ios-package" value="CDVWKWebViewEngine"/>
    </feature>
was added to the config.xml.

and then do iOS Release Build and it genarate .ipa file for upload to apple store but when I upload it to apple store it give that error

**I use phonegal build but today i get this error when upload .ipa to apple store

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability**

I removed all cordova plugins but in monaca build log I see both wkwebview and UIWebview ,how can I remove all UIWebview references.I don't know where UIWebiew generate,I don't use any cordova plugins

In app settings i set WebView Engine to WKWebView

I asked it in community page but no answear yet:https://community.onsen.io/topic/4076/itms-90809-deprecated-api-usage-new-apps-that-use-uiwebview-are-no-longer-accepted-instead-use-wkwebview-for-improved-security-and-reliability

and here is my app url: https://console.monaca.mobi/build/5ef8c3eee78885923d22db61/ios-build

here is my config.xml

<?xml version="1.0" encoding="UTF-8"?>
<widget xmlns="http://www.w3.org/ns/widgets" id="com.demircode.bileteviniz" version="1.3.1">
  <name>BiletEviniz</name>
  <description>BiletEviniz</description>
  <author/>
  <content src="index.html"/>
  <allow-navigation href="*"/>
  <allow-intent href="itms:*"/>
  <allow-intent href="itms-apps:*"/>
  <preference name="Orientation" value="default"/>
  <preference name="loglevel" value="DEBUG"/>
  <preference name="AndroidLaunchMode" value="singleTop"/>
  <preference name="ErrorUrl" value=""/>
  <preference name="Fullscreen" value="false"/>
  <preference name="KeepRunning" value="true"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="1000"/>
  <preference name="AllowInlineMediaPlayback" value="false"/>
  <preference name="BackupWebStorage" value="cloud"/>
  <preference name="FadeSplashScreenDuration" value="250"/>
  <preference name="KeyboardDisplayRequiresUserAction" value="true"/>
  <preference name="MediaPlaybackRequiresUserAction" value="false"/>
  <preference name="SuppressesIncrementalRendering" value="false"/>
  <preference name="TopActivityIndicator" value="gray"/>
  <preference name="GapBetweenPages" value="0"/>
  <preference name="PageLength" value="0"/>
  <preference name="PaginationBreakingMode" value="page"/>
  <preference name="PaginationMode" value="unpaginated"/>
  <feature name="LocalStorage">
    <param name="ios-package" value="CDVLocalStorage"/>
  </feature>

  <preference name="monaca:AndroidIsPackageNameSeparate" value="false"/>
  <platform name="ios">
    <preference name="orientation" value="portrait"/>
    <icon src="lobbe.png"/>
    <icon platform="ios" height="76" src="lobbe-76-76.png" width="76"/>
    <icon platform="ios" height="120" src="lobbe-120-120.png" width="120"/>
    <icon platform="ios" height="152" src="lobbe-152-152.png" width="152"/>
    <icon platform="ios" height="1024" src="lobbe-1024-1024.png" width="1024"/>
    <icon platform="ios" height="40" src="lobbe-40-40.png" width="40"/>
    <icon platform="ios" height="167" src="lobbe-167-167.png" width="167"/>
    <splash src="/res/ios/screen/Default@2x~universal~anyany.png"/>
    <preference name="WKWebViewOnly" value="true"/>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine"/>
    <feature name="CDVWKWebViewEngine">
      <param name="ios-package" value="CDVWKWebViewEngine"/>
    </feature>
    <config-file platform="ios" parent="CFBundleLocalizations" target="*-Info.plist">
      <array>
        <string>tr</string>
        <string>en</string>
      </array>
    </config-file>
  </platform>
  <preference name="WindowsStorePublisherName" value="My Name"/>
  <preference name="WindowsStoreIdentityName" value="3e46a957-1e6e-2eb6-9380-b3b37c4dec02"/>
  <preference name="ios-XCBuildConfiguration-TARGETED_DEVICE_FAMILY" value="1,2"/>
  <preference name="AutoHideSplashScreen" value="true"/>
  <preference name="FadeSplashScreen" value="true"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <access origin="bileteviniz.com"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="EnableViewportScale" value="false"/>
</widget>
and here is my
package.json

{
    "name": "onsenui-video-streaming-app-template",
    "version": "2.0.8",
    "displayName": "OnsenUI Video Streaming Demo",
    "cordova": {
        "plugins": {
            "cordova-custom-config": {},
            "monaca-plugin-monaca-core": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-wkwebview-engine": {}
        }
    },
    "dependencies": {
        "cordova-custom-config": "5.1.0",
        "cordova-plugin-splashscreen": "5.0.2",
        "cordova-plugin-whitelist": "1.3.3",
        "monaca-plugin-monaca-core": "3.3.0",
        "cordova-plugin-wkwebview-engine": "1.2.1"
    },
    "scripts": {
        "monaca:preview": "npm run dev",
        "dev": "browser-sync start -s www/ --watch --port 8080 --ui-port 8081"
    },
    "devDependencies": {
        "browser-sync": "^2.26.7",
        "cordova": "^9.0.0"
    }
}

**Comment by yong-asial** [comment]
@blgsyrmhnds 

Have you tried the following steps?

- Select "Configure -> App Settings for iOS" from the IDE header menu and update the item "WebView Engine" to "WKWebView".   
- For the build environment, select the menu "Build-> Build Environment Settings..." and set "iOS 5.1.1" and "Xcode 11.3".
- Select "Configure -> JS/CSS Components Settings..." and update Monaca Core Utility to version 2.1.0   

Note: This instruction is taken from [Monaca Headline](https://monaca.io/headline/)

(cc @emccorson @keijiodagawa)

**Comment by TRANHV-VFA-DO-NOT-USE** [comment]
@yong-asial i follow your step and build, then i stuck by this error:

```
[15:32:12] ** ARCHIVE FAILED **
[15:32:12] The following build commands failed:
[15:32:12] 	CompileC /Users/builder/Library/Developer/Xcode/DerivedData/project_name-ajoronvfhiolmkdxnnonxjzeeavb/Build/Intermediates.noindex/ArchiveIntermediates/project_name/IntermediateBuildFilesPath/project_name.build/Debug-iphoneos/project_name.build/Objects-normal/armv7/CDVInAppBrowser.o /tmp/download/platforms/ios/project_name/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowser.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[15:32:12] (1 failure)
[15:32:12] xcodebuild: Command failed with exit code 65
```

**Comment by yong-asial** [comment]
@vfa-tranhv Sorry for late reply. It seems it is the build issue. many things could cause the problems. For better support, could you submit us the ticket here - https://monaca.io/support/technical/
