### ISSUE TITLE
Fix normal remote build to follow the behavior of Localkit

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#16]
Currently Monaca CLI's normal remote build does not sync the project with the cloud. Therefore, please fix it to match the behavior as Localkit.
- Upload the changed files before showing remote build dialog.
- Download the changes after closing remote build dialog. (maybe this part is difficult since the app cannot know when the browser is closed.)

**Comment by masahirotanaka** [comment]
I noticed monaca-cli bundles NW.js, so we can display the remote build dialog using NW.js, similar to what Localkit is doing.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

I tried some basic applications that run with node webkit runtime using syntax `nw /path/to/application`.

When the same code (example is given below) is ran from monaca-cli, it couldn't find the required modules and context.
`var nwGui = require('nw.gui');`
 `var aboutWindow = nwGui.Window.open('about.html', params);`

If we managed to write a separate nw application that just opens up Monaca cloud build page and launch it using `spawn` or `exec` we wont be able to connect monaca-cli and browser close event.

Please do let me know your feedback.
