### ISSUE TITLE
Problem with framework7-vue-webpack

### ISSUE THREAD

**Issue by lroal** [monaca/monaca-cli#161]
Can you please upgrade the template framework-vue-webpack to the latest framework7 ?
It does not seem to work after upgrading the framework7 and framework7-vue. I am getting lots of warnings when running it. And it does not build.
I think it would be great if the update procedure of framework 7 was documented in the template. Is it enogh to run npm update on framework7 and the icons ? And then copy the icons to the fonts folder ?

    WARNING in ./node_modules/framework7/css/framework7.css (./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/lib??ref--4-2!./node_modules/framework7/css/framework7.css)
    Module Warning (from ./node_modules/postcss-loader/lib/index.js):
    (Emitted value instead of an instance of Error) postcss-custom-properties: /mnt/c/devel-linux/montest/node_modules/framework7/css/framework7.css:947:3: variable '--f7-page-transition-duration' is undefined and 
used without a fallback

**Comment by yong-asial** [comment]
@lroal I have ported the framework7-vue template to Monaca-compliant template here - https://github.com/yong-asial/framework7-vue-splitter. You can give it a try first.

Otherwise you can wait until I release the official one to Monaca later.

**Comment by lroal** [comment]
That is great ! I will test it by the END of the day.

**Comment by yong-asial** [comment]
@lroal We are getting closed to release to production for both monaca-cli and monaca cloud IDE. You also could try clone it from this official repo https://github.com/monaca-templates/framework7-vue-split-view as well.
