### ISSUE TITLE
Remote build doesn't have `debugger`

### ISSUE THREAD

**Issue by j4hangir** [monaca/monaca-cli#168]
The only options are:

![image](https://user-images.githubusercontent.com/7769125/106396224-efc24600-6406-11eb-975f-8eb7890592e6.png)

Why's `debugger` version not enlisted though?

**Comment by yong-asial** [comment]
@j4hangir we have supported it `debugger` build now for both iOS and android.

- `monaca remote build --browser` --> then at least build `debugger` once in the cloud (for example, select proper certificate and settings)
- next time, you can just run `monaca remote build android --build-type=debugger` or `monaca remote build ios --build-type=debugger`
