### ISSUE TITLE
"Your project is missing splash screens and/or icons" with remote build ios

### ISSUE THREAD

**Issue by maurovanetti** [monaca/monaca-cli#173]
Whenever I call `monaca remote build ios` on a Monaca project I get the following error message:

> Your project is missing splash screens and/or icons. Please add the missing files from remote build settings by executing `monaca remote build --browser`.

The icons and splash screens are actually there, though, and I can build the project from the Monaca Cloud IDE with no issues.

**Comment by yong-asial** [comment]
@maurovanetti Thank you for reporting. We have fixed the problem now. Please try again.

**Comment by maurovanetti** [comment]
Great! The remote build is working again now.
