### ISSUE TITLE
monaca import initial location

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#2]
Currently, monaca import does not have the default value for the directory, thus just hitting Enter will result in messing up the current directory.

I would like to have the project name as the initial directory, and allow the user to edit using cursor and backspace keys.

Moreover, if the directory is already existing, please do not proceed to download to that specific directory but show an error message and ask the directory again.

**Comment by argelius** [comment]
Thanks! I will fix this.

**Comment by argelius** [comment]
@masahirotanaka I changed this and some other things suggested by @khemry and bumped to 1.0.1.
