### ISSUE TITLE
Ask again if the input is invalid

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#21]
Some places in user inputs will halt the command instead of asking the user again.

I noticed that in `monaca import` and hit Enter without specifying project number.
Please find similar places and fix them to ask the user again.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

I have implemented this for `monaca import` and `monaca clone` command. This mechanism is already in place for `monaca create` command.

Apart from number inputs, users are asked for string inputs like destination directory name, y/n for confirm commands; no change is made for such inputs.
