### ISSUE TITLE
Fix monaca create to include project name

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#24]
When creating a project in `monaca create`, the application name is not reflected in the project.

After creating the project, please modify `config.xml` `<name>` element to include the user specified name. Just don't forget to escape entities before injecting to the XML file.

http://stackoverflow.com/questions/7918868/how-to-escape-xml-entities-in-javascript

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka,

If we replace these escape characters manually then it creates a mess. I have used `DOMParser` and `XMLSerializer` from `xmldom` package. It takes care of the escape entities by itself. 

E.g. 
command `monaca create "vinayak's & <mote>"` inserts `vinayak's &amp; &lt;mote>` into config.xml and a project is created on Monaca Cloud with exact given name once it is uploaded/built.

![screen shot 2015-08-19 at 3 52 08 pm](https://cloud.githubusercontent.com/assets/5630856/9354011/7d0fa73c-468a-11e5-8ad6-37e1f1a82dd3.png)
