### ISSUE TITLE
Remove remote build timeout

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#26]
Currently monaca-lib has specified the timeout value to 80 seconds when running an automatic remote build. Please fix monaca-lib so that monaca-cli will keep waiting until remote build is finish.

**Comment by JW-Vinayak** [comment]
@masahirotanaka , do you mean we just remove the timeout from monaca-lib and theoretically allow monaca-cli to wait infinitely (worst-case scenario) ?

**Comment by masahirotanaka** [comment]
Right. Not a big change actually.
