### ISSUE TITLE
Monaca upload sometimes gets the open error

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#27]
In some situations, `monaca upload` raises `Error: EMFILE, open 'XXXXX'` error.
It was occurred by one of the user using under Mac OS X, when many additional directories (/test, /jsdoc and like) and files are in the project directory. 

Maybe difficult to reproduce, but please see how it will happen, and fix the issue.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka ,

Just went through `uploadProject()` code in `monaca-lib` and found out that it allows only files in /www, /merges and /plugins folders and selected few files in /platforms directory. So this invalidates above mentioned scenario as I have tested it.

I will now test with huge number of files in /www and see if I can replicate the issue.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka ,

I tested by uploading 1000 `.txt` files and it failed at file no. 234, giving error `Error: EMFILE` ( too many files are open). After I added `qLimit` to code, `monaca upload` works fine irrespective of number of files being uploaded.
