### ISSUE TITLE
Imported/Cloned projects have empty project names

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#28]
For imported/cloned projects, there are 3 "config.xml" files:
-config.android.xml (empty project name)
-config.ios.xml (empty project name)
-config.xml (default project name)

==> In Monaca Debugger, those projects have no project name.

**Comment by JW-Vinayak** [comment]
Hi @khemry,

I did not get what the issue exactly is. If a file is imported/cloned then it by default has name of the project in config.xml file and it is sent to debugger properly, I checked it on my device.

**Comment by khemry** [comment]
Hi @JW-Vinayak,

When I cloned/imported a project into my local PC and run it on Monaca Debugger, it has no project name. Then, I checked config.ios.xml and config.android.xml files. I found tha thet project name is empty. Please refer to the screenshots below.
![config android xml](https://cloud.githubusercontent.com/assets/3192899/9459840/f1bd827a-4b3a-11e5-8be1-c6faab11dd0b.png)
![config ios xml](https://cloud.githubusercontent.com/assets/3192899/9459841/f1c23806-4b3a-11e5-9b9c-064748294fe3.png)
![debugger](https://cloud.githubusercontent.com/assets/3192899/9459842/f1c42418-4b3a-11e5-93f3-74f589e0be96.png)

**Comment by JW-Vinayak** [comment]
Thanks for this info @khemry. Does this imported/cloned project have config.xml file with actual project name?

**Comment by khemry** [comment]
@JW-Vinayak :

Yes, there is a config.xml file with actual project name insides www folder of the cloned project.
![screen shot 2015-08-25 at 3 14 55 pm](https://cloud.githubusercontent.com/assets/3192899/9459960/2f07a632-4b3c-11e5-9243-fd054476e150.png)

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

Since these *config.xml files are donwloaded from Monaca cloud, do we fix this issue in monaca-cli or on cloud?

**Comment by khemry** [comment]
@JW-Vinayak :

I tried cloning again today and it seems like there is no such issues anymore. Thank you.
