### ISSUE TITLE
Failed to Open the Project with Sublime

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#32]
I successfully added Sublime in the "Open in ..." feature. However, when I tried opening the project with it, this error occurred (see the screenshot).
![screen shot 2015-09-07 at 12 50 06 pm](https://cloud.githubusercontent.com/assets/3192899/9709028/4f4b0a74-555f-11e5-9083-684a16c49c9f.png)

**Comment by masahirotanaka** [comment]
Vinayak, please take a look at it.

**Comment by JW-Vinayak** [comment]
Hi @khemry,

Can you please provide more details like which version of sublime text (2 or 3) you added manually?  and what are the arguments that you used? A screenshot is much appreciated.

P.S. This issue belongs to monaca_localkit repository.

**Comment by khemry** [comment]
Hi @JW-Vinayak,

OMG. Sorry I placed the issue in the wrong repository. >.<
I'll move it there and provide you more information regarding this issue.
