### ISSUE TITLE
"monaca download --delete" is not working as intended

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#36]
"monaca download --delete" is supposed to delete local files which are not existed on Monaca Cloud. However, it doesn't do anything regarding those locally existed files. It seems like it can't detect those files. Please confirm this.

**Comment by JW-Vinayak** [comment]
Hi @khemry,

Can you please tell me if you are talking about any specific file that `monaca download --delete` is not deleting or is it not deleting at all?

Screenshot of your folder structure will be appreciated. Also please make sure that you have not mentioned those files/folders in `.monacaignore` file

**Comment by khemry** [comment]
Hi @JW-Vinayak :

So here is how this issue happens:
1. I cloned a Memo Application from Monaca Cloud.
2. Then, I added a new local file inside Memo Application, called "new_local.html".
3. I added a new file, called "test.html" in the Memo Application in Monaca Cloud.
4. When I run "monaca download --dry-run --delete" in my local PC, it is supposed to show

```
    Following files will be downloaded.
    1. /www/test.html

    Following files will be be deleted locally.
    1. /www/new_local.html
```

However, it seems like it couldn't detect the new local file which is not existed in the Cloud. It just showed:

```
    Following files will be downloaded.
    1. /www/test.html

    No files will be deleted locally.
```
1. Then, I run "monaca download --delete" just to confirm if the "new_local.html" is deleted or not. As expected, only "test.html" is downloaded and the "new_local.html" is not deleted.
   ![cloud](https://cloud.githubusercontent.com/assets/3192899/10126802/5a950496-65d3-11e5-83e2-5f7093c2d775.png)
   ![local](https://cloud.githubusercontent.com/assets/3192899/10126803/5a99b9a0-65d3-11e5-802d-aefaab17862a.png)

**Comment by JW-Vinayak** [comment]
Hi @khemry,

I just tried the scenario you mentioned at it works as expected as shown below.
![screen shot 2015-09-28 at 11 58 33 am](https://cloud.githubusercontent.com/assets/5630856/10129145/95f349b2-65d8-11e5-8900-cac839daf66e.png)

Please make sure that you have not written any rule in `.monacaignore` file which is not allowing this file to be deleted.

**Comment by khemry** [comment]
Hi @JW-Vinayak : 

Hmmm... Now I don't understand why it doesn't work correctly in my PC. I've not written any rule in .monacaignore file.

Where can I find .monacaignore file?

I tried to re-install monaca cli and re-do the same scenario again. It is still not deleting the local file.

**Comment by JW-Vinayak** [comment]
`.monacaignore` is created by user if he/she wants some files to be ignored while upload and download operations.

Well another area to look for would be to make sure that your monaca-cli is pointing to correct/latest version of monaca-lib.

**Comment by khemry** [comment]
@JW-Vinayak 

I re-installed monaca cli. It still doesn't fix this.
Its version is 1.2.4

**Comment by JW-Vinayak** [comment]
Hi @khemry,

Please try pointing monaca-cli to monaca-lib version 1.1.6. Please refer to this [change log](https://github.com/monaca/monaca-lib/commit/f9be8a1a07a5c458193796d4518ac0d9d479ef6c).

**Comment by argelius** [comment]
Hi @JW-Vinayak @khemry 

I debugged it quickly on Khemry's machine.

I saw that at this line:
https://github.com/monaca/monaca-lib/blob/master/src/monaca.js#L1449
the `allowFiles` variable was just an empty string. This means that it will never remove any files regardless of what you do.

I also took a look at the `_filterIgnoreList()` method and it looks like it will always return an empty list.

This `if` statement will always be false if there is no `.monacaignore` file:
https://github.com/monaca/monaca-lib/blob/master/src/monaca.js#L228

This `if` statement will always be false since it didn't enter the first one.
https://github.com/monaca/monaca-lib/blob/master/src/monaca.js#L239

Which means that it will always return `[]` if there is no `.monacaignore` file.

**Comment by JW-Vinayak** [comment]
Hi @argelius,

Thank you for pointing out the bug, I have fixed it in this [pull request](https://github.com/monaca/monaca-lib/pull/29).
