### ISSUE TITLE
monaca plugin

### ISSUE THREAD

**Issue by khemry** [monaca/monaca-cli#5]
$ monaca plugin: doesnt list the installed plugin

$ monaca plugin add : I think we need to mention path. github path?

$ monaca plugin search <query> : search for plugin in where? where is that plugin directory? Plugin registry? the description makes it sounds like it's searching in my own local plugin directory which is not true as I tried.

$ monaca plugin rm : how to use this? I tried path, or plugin name but it's not working

**Comment by argelius** [comment]
Thanks @khemry! I'll take a look at this on Monday.

**Comment by argelius** [comment]
Fixed docs.

I wrote "plugin directory" but I meant "plugin registry".
