### ISSUE TITLE
monaca preview --no-open

### ISSUE THREAD

**Issue by frandiox** [monaca/monaca-cli#55]
@masahirotanaka Please have a look at #53 and tell me your opinion. Maybe we can avoid opening browsers by defult and open it with `-o`?

**Comment by masahirotanaka** [comment]
I saw it. I think it's better to open the browser by default (preserving the current default for now). However, I think it makes more sense if doing some work to print out a message in the command line to hint the user how to prevent the browser from opening.

**Comment by frandiox** [comment]
@masahirotanaka Do you mean you want to implement some kind of `--no-open` parameter?

**Comment by masahirotanaka** [comment]
Yes, I think his proposal of adding `--no-open` (and `-no`) makes sense.
