### ISSUE TITLE
monaca remote build command problem

### ISSUE THREAD

**Issue by sijad** [monaca/monaca-cli#60]
when I try `remote build android` or `remote build ios` I get this:

``` text
ReferenceError: deferred is not defined
```

tried with both node v6.2.2 and v4.4.7

**Comment by frandiox** [comment]
@sijad Thank you for the report, this will be fixed for the next release.

**Comment by svdoever** [comment]
Having the same with `monaca signup`, `monaca login` etc. only `monaca preview` is working.
I use NodeJS version 6.2.1.

**Comment by frandiox** [comment]
This has been fixed in [monaca-lib 2.0.6](https://github.com/monaca/monaca-lib). This will be included in the next CLI version after some more tests.

**Comment by frandiox** [comment]
@sijad @svdoever This should be fixed in the last release we made a couple days ago. Please confirm it :)
