### ISSUE TITLE
Where can I find the log file

### ISSUE THREAD

**Issue by geohuz** [monaca/monaca-cli#67]
I got error when using monacan preview, but I'm not able to find the log:

```
Failed to transpile: Error has occured while transpiling /Users/geohu/Codings/essMobile/essmb with webpack. Please check the logs.
```

could somebody help me out?

Thanks!

**Comment by masahirotanaka** [comment]
@geohuz We just published new Monaca CLI (Version 2.1.0). Can you please check if the latest version works? We switched to using webpack-dev-server if it is running with React and Angular 2.
