### ISSUE TITLE
don't build really file with 'monaca serve'

### ISSUE THREAD

**Issue by rdlabo** [monaca/monaca-cli#73]
現在、`$monaca preview`と`$monaca transpile`で明確に役割が分かれており、
- preview時はLiveLoadが働くものの実在ファイルは生成されない
- transpile時は、実在ファイルが生成されるが、LiveLoadされない

という状態になっています。しかし、PWAの流れを受けて今後「一旦、Webアプリを公開して、同様のものをハイブリッドアプリでつくる」需要が高まることを考えると、この二者を分けることには明確なメリットはなく、以下の2つの問題を抱えています。
- 最新Chromeでエレメント生成ができないように、同様のことが起きると当該ブラウザでは確認しようがない
- 初心者からすると、「見えてるファイルは、実在ファイルだと思う」

---

そこで、
- preview は、LiveLoad + 実在ファイルのbuild
- transpile(prod) は実在ファイルのbuildのみ

と区分を分けた方がすっきりするのではないでしょうか。

以上、提案申し上げます。

**Comment by asial-matagawa** [comment]
@erisu @masahirotanaka @frankdiox @andipavllo 

I have translated and summarized the issue message from Japanese to English.

**ISSUE SUMMARY**

> `monaca transpile` generates files into a real file system, but `monaca preview` does not.
> `monaca preview` seems to use in-memory files.
> 
> This behavior has two problems below:
> 1. Hard to debug. Users cannot read in-memory files generated by `monaca preview`.
> 2. Confusing. When a user see `monaca preview` running, the user is likely to assume that the generated files in a real file system.
> 
> Then I think it would be nice if `monaca preview` always generates files into a real file system.

**Comment by asial-matagawa** [comment]
I will translate English to Japanese (and Japanese to English), so please feel free to write replies in English.

**Comment by asial-matagawa** [comment]
@rdlabo 

本件について @masahirotanaka, @frankdiox と相談した結果をお伝えします:
- `monaca preview` の仕様は、現在 `monaca preview` の内部で利用している webpack-dev-server の仕様に引きずられている
- そのため webpack-dev-server が「実在ファイルを生成しない」という仕様である以上、**デフォルトの** `monaca preview` を「LiveLoad + 実在ファイルのbuild」という仕様にすることはできない
- **オプションとして** なら「LiveLoad + 実在ファイルのbuild」の実装は可能であるため、実装を検討する
  - その際は webpack-dev-server 以外のローカル HTTP サーバを立ち上げることになる
- webpack-dev-server の利用を廃止するという手もあるが、webpack-dev-server は React アプリ開発におけるデファクトスタンダードであるため難しい
- `monaca preview` および Monaca CLI 全体の吐くメッセージが初見のユーザにとって非常に分かりにくいというのが今回の問題の根底にあるので、
  ユーザを混乱させないよう、メッセージの改善を行う

現状は React ユーザーに寄りすぎている面がありますので、今後は Angular 2 ユーザーにも配慮した設計に寄せていきたいと思います。
（Onsen UI 2 本体の改善も並行してやっているのでなかなか時間が取れないですが……）
貴重なご意見をありがとうございます。
