### ISSUE TITLE
Cannot find module 'source-map' when I run monaca preview

### ISSUE THREAD

**Issue by mishra93mohit** [monaca/monaca-cli#76]
Hi Guys,

When I try running monaca preview it shows me error 'cannot find module source-map'. I installed the module manually but still issue persist.

![capture](https://cloud.githubusercontent.com/assets/10059688/21177463/54582b4e-c211-11e6-9a01-23416a09aea6.PNG)

Please let me know if there is any work around or fix for this.

Thanks

**Comment by andipavllo** [comment]
We made some changes to the embedded HTTP Server recently, could you please try again with the latest version of Monaca CLI?
