### ISSUE TITLE
plugin add command doesn't add plugin to project_info.json

### ISSUE THREAD

**Issue by tiibun** [monaca/monaca-cli#77]
Hi,
I did `monaca plugin add cordova-plugin-camera`,
And `monaca upload`.
But Camera Plugin is not enabled in monaca cloud IDE.
I think the plugin name should be added .monaca/project_info.json.

- Version
2.1.7
- OS
Windows10

Thanks

**Comment by andipavllo** [comment]
Sorry for the late reply.
In order to use the plugins in Monaca Cloud you should add them directly in the cloud environment and need a [paid plan](https://monaca.io/pricing-detail.html).
You can run `monaca remote build --browser` and navigate to the Cordova Plugin management page.
