### ISSUE TITLE
Webpack - Use dev config instead of prod config on monaca debug

### ISSUE THREAD

**Issue by Grsmto** [monaca/monaca-cli#80]
Hi,

First thanks for the good work, Monaca seems really cool so far.
I'm working on an app in React with the Webpack template and I noticed that `monaca debug` is using the production environment (ie webpack.prod.config.js).
It should use the development environment so the build would be much faster for development (live-reloading), from my tests build goes from 30s to 0.5s by disabling the minification for example.
Also it could make sourcemap work (but I was unable to make it work I don't know why... :( )

**Comment by frandiox** [comment]
@Grsmto Hey, thanks for the feedback! I think the main reason why Monaca uses production version is that it needs the generated files in the filesystem. Development keeps everything in memory to make it faster, so it wasn't possible to transfer the files to the device.

If I don't remember wrong, the first build was kind of slow, from 10 to 40 seconds depending on your machine, but the subsequent changes should be quite quick, right?

It uses already cache in production to make it faster. Perhaps we can disable minification for debugger as well. We'll have a look at it, thanks!
