### ISSUE TITLE
Vue DevTools

### ISSUE THREAD

**Issue by misterjunio** [monaca/monaca-cli#84]
Create a new Monaca project with the Vue minimum template and then run `monaca preview`. Chrome does not pick up the Vue DevTools extension. I found out that by removing `webpack-dev-server/` from the URL the extension is enabled but this is a bit of a pain and I don't know if it doesn't possibly break other things.

**Comment by frandiox** [comment]
@misterjunio `/webpack-dev-server/` is an iframe! Can you try this solution? https://github.com/vuejs/vue-devtools/issues/203

**Comment by misterjunio** [comment]
@frandiox like I said removing `webpack-dev-server/` from the URL works and apparently it keeps the hot reloading and all, just thought there would be some Webpack config with which that wouldn't be necessary. The `{inline: true}` trick didn't work but I guess it's fine then. Thanks 😄
