### ISSUE TITLE
Debugger not working with 2.2.4

### ISSUE THREAD

**Issue by hirbod** [monaca/monaca-cli#92]
Hi,

I've wasted like 5 hours to get the debugger working - just figured out the crash happened due to update to 2.2.4 (can't get project information error)

It just freezed for minutes. After downgrading to 2.2.3, everything works as expected

**Comment by andipavllo** [comment]
We will immediately check it and provide a fix as soon as possible. Sorry for the trouble.

**Comment by hirbod** [comment]
Just as a sideinfo: it did not work in any project, not even in newly created demo apps like splitter or tabs etc.

**Comment by andipavllo** [comment]
@Hirbod I just fixed this and released CLI 2.2.5
Please let me know if you still have any problem.
