### ISSUE TITLE
Monaca Emulate iOS

### ISSUE THREAD

**Issue by hirbod** [monaca/monaca-cli#93]
Just query:

```bash
monaca emulate ios
cordova-custom-config: Skipping auto-restore of config file backup(s)
Error: cordovaProject.projectConfig.getFileResources is not a function
```

Just removed custom-config plugin, same issue!

**Comment by andipavllo** [comment]
`monaca emulate` is actually the same as `cordova emulate` and uses the built-in Cordova CLI (6.2) in Monaca CLI.
It seems that Cordova CLI 6.2 has the same bug reported for multiple commands that are platform related. For example, take a look at the [following issue](https://issues.apache.org/jira/browse/CB-12633).
One solution would probably be to install the latest Cordova CLI and execute `cordova emulate ios` command on it
